name: Replay
main: Prim69\Replay\Main
version: 4.20.69-ALPHA-69
api: 3.0.0
author: xPrim69x
mcpe-protocol: [440]
description: A plugin made to replay or record other players' actions!
website: https://www.github.com/Prim69/Replay
permissions:
  replay.command:
    description: Permission to use the replay command!
    default: op
